### ISSUE TITLE
When on tags tab, there is blank extra space beneath.

### ISSUE THREAD

**Issue by Kav91** [newrelic/nr1-container-explorer#10] opened 2019-09-11 05:49 UTC
Only occurs when on the tags tab, "processes" and "charts" tabs are okay.

![image](https://user-images.githubusercontent.com/13043208/64671334-704b7400-d4ab-11e9-9940-68531620f717.png)

**Comment by danielgolden** [comment] 2019-10-02 13:13
I know what the problem is, so I'll submit a PR that includes this fix soon.

**Comment by danielgolden** [comment] 2019-10-28 10:41
Fixed in #19

**Closed by danielgolden** 2019-10-28 10:41 UTC
